volumes: 
  pg_data:
  static:
  images:

services:
  db:
    image: postgres:14
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend
    env_file: ../.env
    volumes:
      - static:/static
      - images:/app/images
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static:/static
  nginx:
    build: ./
    env_file:
      - ../.env
    ports:
      - "80:80"
    volumes:
      - static:/static
      - images:/app/images
      - ../docs/redoc.html:/static/redoc.html:ro
      - ../docs/openapi-schema.yml:/static/openapi-schema.yml:ro
    depends_on:
      - backend
