# Generated by Django 5.2.8 on 2025-11-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('author', 'subscriber')},
        ),
    ]
