# Generated by Django 5.2.8 on 2025-11-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_follower_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
